/**
 * Article Search Data
 *
 * Auto-generated by generate-search-data.js
 * DO NOT EDIT THIS FILE MANUALLY
 *
 * To update this file:
 * 1. Edit article HTML files in /articles/
 * 2. Run: node scripts/generate-search-data.js
 *
 * Articles are automatically sorted by date (newest first)
 */

const allArticles = [
    {
        "title": "My job is internet",
        "description": "I used to be internet famous, and now I help other people become internet famous—which might be the perfect ending to that story.",
        "content": "I used to be internet famous, and now I help internet-famous people stay authentic and actually deliver value to their audiences—which might be the perfect ending to that story. One way to measure growth is to be uncomfortable. I've been forcing myself to get out of my comfort zone this past year: going to more events, trying new hobbies, doing more things by myself, and most importantly, writing more. (Sure, it's AI-assisted, but I promise I always write the first draft myself!) And thus, I dec",
        "url": "articles/my-job-is-internet.html",
        "date": "2025-10-26"
    }
];

// Format date to readable format (e.g., "Oct 2025")
function formatDate(isoDate) {
    const date = new Date(isoDate);
    const months = ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec'];
    return `${months[date.getMonth()]} ${date.getFullYear()}`;
}

// Export for use in other scripts (if needed)
if (typeof module !== 'undefined' && module.exports) {
    module.exports = { allArticles, formatDate };
}
